### PR TITLE
allow guzzlehttp/psr7 v2

### PR DESCRIPTION
**Pull request by Nielsvanpach**
Yesterday 2.0 was released: https://github.com/guzzle/psr7

### CODE REVIEW

**Comment by zbateson** [comment]
Wonderful, thanks for that!

**Comment by Nielsvanpach** [comment]
Any idea when this will be released?

**Comment by zbateson** [comment]
It'll need a bit more work -- my other library, zbateson/stream-decorators (a dependency of mmp) is using guzzle/psr7 v1.0 also, so this change alone isn't enough.

Unfortunately zbateson/stream-decorators errors out with 2.0.  All of the errors so far are:

``` Error: Call to undefined function GuzzleHttp\Psr7\stream_for() ```

If that's all it is shouldn't take too long to resolve but I suspect there'll be other things too.

**Comment by zbateson** [comment]
Released in 1.3.2.

Thanks again :)

**Pull request merged**
