### PR TITLE
Create Header.php

### PR DESCRIPTION
**Pull request by ThomasLandauer**
First step of https://github.com/zbateson/mail-mime-parser/issues/121

### CODE REVIEW

**Comment by ThomasLandauer** [comment]
Sorry, I forgot that GitHub doesn't send me a notification when you react with an emoji. So I was waiting for you to merge it, while you were probably waiting for me to finish it ;-)

Questions:

1. On https://github.com/zbateson/mail-mime-parser#usage you're mixing lower-case and uppercase (`subject` vs. `Content-Type`). I went for lower-case now (`message-id`). Or do you think we should use the case of the very header itself (`Message-ID`)? In the end, it doesn't matter, since you're doing `strtolower()` in [`HeaderFactory::getNormalizedHeaderName()`](https://github.com/zbateson/mail-mime-parser/blob/master/src/Header/HeaderFactory.php#L114)  
BTW: php-mime-mail-parser is doing the same in [`Parser::getRawHeader()`](https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/release-6.0.0/src/Parser.php#L232) :-)
2. Which headers should get a `const`? All mentioned in the table in [RFC 5322](https://tools.ietf.org/html/rfc5322#section-3.6)?

**Comment by zbateson** [comment]
Gah, I don't remember seeing an email with your updates too lol.

For the first point, yeah -- I'm mixing it intentionally there to show that the case doesn't matter.

For the second, I guess that would be ideal if it included all of those :+1: I can't think of a better way to set which ones should or shouldn't be available, so to me that makes sense :)

Thanks again,
Zaahid

**Comment by ThomasLandauer** [comment]
I mentioned this before at https://github.com/zbateson/mail-mime-parser/pull/129#issuecomment-671940793 - can you configure Nitpick to explicitly mention the line number? I never know where the error is:
Screenshot_20201007_202937

* I went for "RFC-case" now (e.g. "Content-Type"), to try to somehow make clear what the field "name" is (e.g. "orig-date"), and its corresponding header syntax ("Date").

* Should I move the file up to its parent directory, so it's gonna be
  ```php
  use ZBateson\MailMimeParser\Header;
  ```
  instead of
  ```php
  use ZBateson\MailMimeParser\Header\Header;
  ```
  ?

**Comment by zbateson** [comment]
Hi @ThomasLandauer --

This is looking good, thank you!

For Nitpick and line numbers, if you look at the comment in your commit, the Nitpick comment is directly below the line in question.  I'm not aware of any additional configuration to get it to be more explicit (or can't find any, the website doesn't have much info on it).

For the second part, actually I'd prefer renaming the class to 'HeaderConsts' to avoid confusion as it doesn't represent a 'header object' (like for instance ZBateson\MailMimeParser\Message) does.  Does that make sense to you? (Or HeaderNames or something?)

**Comment by ThomasLandauer** [comment]
Let's start with the least important - Nitpick: Maybe you can open a ticket there. When they show *4* lines, it's obvious that they're giving some context above/below the actual error line. But the question is: above or below? ;-)

Class name: Let's see how it will look in action:
```php
$message->getHeaderValue(Header::SUBJECT);
$message->getHeaderValue(HeaderConsts::SUBJECT);
$message->getHeaderValue(HeaderNames::SUBJECT);
$message->getHeaderValue(AbstractHeader::SUBJECT);
```
Which looks best to you? I went for `Header` cause it has the best semantics in the actual usage context.  
To "internally" rectify the name, you can `extend` all real header classes from it - ha, ha :-)

**Comment by zbateson** [comment]
Hmmmm... so annoying that none of them are perfect "looking" to me except Header, but yeah it doesn't make sense to do that.

I think out of those four my preference is ``` HeaderConsts::SUBJECT ```.  It can't be confused for anything else other than a class of constants that doesn't/shouldn't be instantiated hehe.

**Comment by ThomasLandauer** [comment]
Well, what I wanted to showcase is that from a user's perspective, `Header::SUBJECT` is the only one that makes sense.

>  It can't be confused for anything else other than a class of constants that doesn't/shouldn't be instantiated hehe.

Well, nobody (besides you) is going to instantiate any of those classes. And since it's `abstract` anyway, I'd say this is clear in any case.

So my favorite is still `Header`. But you're the boss - tell me what you want, and let's merge it :-)

**Comment by zbateson** [comment]
That's true you won't be instantiating them, but you could be using them as method parameters/need to know hierarchy a little bit at least, in which case (to me) the existence of a Header class that doesn't follow what a Message class is would seem off.  Let's go with HeaderConsts.

Thanks again :)

**Comment by ThomasLandauer** [comment]
There you go :-)

Question about README: What shall we do with this?:
> echo $att->getHeaderParameter(
    'content-type',
    'charset'
);

**Comment by zbateson** [comment]
Looks good, thanks @ThomasLandauer --

For the readme, I think it's still beneficial to know the use of the consts is optional, and you can choose to use them or pass a string directyl (some may prefer that, plus useful to know if you're looking for a 'X-Some-Undocumented-Header' or something).

The last line is fine as-is for that reason too... maybe keep 'cc' and 'content-type' examples without the consts?

**Comment by zbateson** [comment]
Perfect, thank you!

**Comment by ThomasLandauer** [comment]
> For the readme, I think it's still beneficial to know the use of the consts is optional

Good point - this got lost in my mind...
But *mixing* both ways might be more confusing than before...

So I'd say: Clearly recommend the `const`s whenever they exist. For other headers, I added `echo $message->getHeader('X-Foo');`. Is it `getHeader()` or `getHeaderValue()` in this case?

Damn - you already answered before I even sent it! :-(

**Comment by ThomasLandauer** [comment]
What I forgot yesterday: Since this is now public in README - will you make a new release soon? Otherwise you should revert README for now, to avoid confusion.

**Comment by zbateson** [comment]
ugh, yeah that's a good point.  I need to look at a couple issues before releasing and it may take me a little time, so I'll revert for now.

**Pull request merged**
