### PR TITLE
PHP 8.0 support

### PR DESCRIPTION
**Pull request by phpfui**
Changed SplFixedArray::fromArray to new ArrayIterator for PHP 8.0

 * Unit tested on 7.1 and higher
 * My editor removes trailing spaces, but I think that is correct.

### CODE REVIEW

**Comment by phpfui** [comment]
A merge and version would be greatly appreciated by all!

Thanks for this amazing package.  Really helps dealing with reading mail.

**Comment by zbateson** [comment]
Should a new version wait considering php8 still isn't released?  What if other changes are needed anyway -- just wondering on the value of creating a new version for this change when the only change in it is a fix for an unreleased version of php.  Happy to do it if there's a need/reason tho :)

**Comment by phpfui** [comment]
PHP 8.0 was released last week. [Supported PHP versions](https://www.php.net/supported-versions.php), but the issue is TravisCI is a bit behind.  Apparently the nightly build is 8.0 beta of some sort.  In the past it has taken them a few weeks to support the latest release.

Since this is a minor fix, and backward compatible with older versions of PHP, I would say just release it as 1.3.1, and then people on PHP 8.0 projects can upgrade to it.  Since the current version is blowing up after successfully installing under PHP 8,0, I would think you would want to do this ASAP.

And thanks for merging!  I will all projects would do this.

**Comment by zbateson** [comment]
Aah, I didn't realize it was already released.  New version coming, thanks for clarifying :)

**Pull request merged**
