### PR TITLE
Add Return-Path to the list of Address headers

### PR DESCRIPTION
**Pull request by mariuszkrzaczkowski**

### CODE REVIEW

**Comment by zbateson** [comment]
Wonderful, makes sense, thank you!

**Comment by mariuszkrzaczkowski** [comment]
when will a version with this change be published?

**Comment by zbateson** [comment]
As there's nothing else going on, I'll release it right away

**Comment by zbateson** [comment]
Released in 1.2.3, thanks again :+1:

**Comment by mariuszkrzaczkowski** [comment]
thanks a lot, i needed that

**Pull request merged**
