### PR TITLE
fix: type hinting in Message.php

### PR DESCRIPTION
**Pull request by DRoet**
My editor (phpStorm) wasn't able to pick up certain types, this is my attempt at fixing them.
Please let me know if this is OK

Thank you,

Daan

### CODE REVIEW

**Comment by zbateson** [comment]
That's great, definitely needed a cleanup.  Did you want to push more commits to this pull request, or did that cover everything for now?

Thanks,
Zaahid

**Comment by zbateson** [comment]
Actually I'll leave this pull request open till I have something to release (at least a few weeks I imagine), that gives you time to add more to it if you find anything else.

**Comment by DRoet** [comment]
This should cover everything in `message.php` atleast, I have a very limited use-case for this library so this was all that I found.

great work btw,

Daan

**Comment by adityagaurav2018** [comment]
https://yttechcreation.blogspot.com/2019/04/website-speed-test.html

**Pull request merged**
